# Generated by Django 3.1.7 on 2021-05-13 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210422_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camisa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Fecha_Entrada', models.DateField()),
                ('Cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Estampados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Talla', models.CharField(max_length=6)),
                ('Descripcion', models.CharField(max_length=200)),
                ('TCamisa', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='home.camisa')),
            ],
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='categoria',
        ),
        migrations.RenameModel(
            old_name='Categoria',
            new_name='Tela',
        ),
        migrations.DeleteModel(
            name='DatosProducto',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
        migrations.AddField(
            model_name='estampados',
            name='tela',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.tela'),
        ),
        migrations.AddField(
            model_name='camisa',
            name='tela',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.tela'),
        ),
    ]
